# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Censoring Function in C++
#' @name censor_func
#' @description Artificial censoring C++ function
#'
#' @param sw_data A dataframe with the columns needed in censoring process
#' @keywords internal
NULL

censor_func <- function(sw_data) {
    .Call('_TrialEmulation_censor_func', PACKAGE = 'TrialEmulation', sw_data)
}

